---
apiVersion: v2
appVersion: 1.0.1
dependencies:
  - condition: minio.enabled
    name: minio
    repository: oci://registry-1.docker.io/cloudpirates
    version: 0.3.0
  - condition: postgres.enabled
    name: postgres
    repository: oci://registry-1.docker.io/cloudpirates
    version: 0.7.2
  - condition: redis.enabled
    name: redis
    repository: oci://registry-1.docker.io/cloudpirates
    version: 0.5.0
description: Outline is a fast, collaborative, knowledge base for your team built using React and Node.js.
home: https://www.getoutline.com
icon: https://www.getoutline.com/images/logo.svg
# image: outlinewiki/outline
keywords:
  - outline
  - wiki
  - docs
maintainers:
  - name: Budavári Schönherz Stúdió
    url: https://github.com/BSStudio/helm-charts
name: outline
sources:
  - https://github.com/BSStudio/helm-charts/tree/main/charts/outline
  - https://github.com/outline/outline
type: application
version: 1.2.2
